spring:
  application:
    name: DiscoveryServer
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    wait-time-in-ms-when-sync-empty: 100
logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG